### ISSUE TITLE
Support rename-dependency cargo feature

### ISSUE THREAD

**Issue by jonhoo** [RazrFalcon/cargo-bloat#20]
Cargo recently got support for [renaming dependencies](https://github.com/rust-lang/cargo/blob/0dd53841d30816ec0d79d879de71d7adc360bdc5/src/doc/src/reference/unstable.md#rename-dependency). That is, you can do:
```toml
cargo-features = ["rename-dependency"]
# ...
[dependencies]
bar = { version = "0.1", package = "foo" }
```
To import the crate `foo` under the name `bar`. However, this seems to confuse `cargo-bloat`, which reports:
```
error: failed to parse manifest at `/home/jon/dev/projects/distributary/benchmarks/Cargo.toml`

Caused by:
  unknown cargo feature `rename-dependency`
```
